-- jOOQ DDLDatabase codegen source
-- Only the tables used by notification adapters (UserContactPersistenceAdapter, ServiceChangePersistenceAdapter)
-- Written in standard SQL compatible with jOOQ's DDLDatabase parser.

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(20)  NOT NULL,
    provider_id VARCHAR(100) NOT NULL,
    email_enc   VARCHAR(4000),
    email_hash  VARCHAR(64),
    phone_enc   VARCHAR(4000),
    phone_hash  VARCHAR(64),
    nickname    VARCHAR(100),
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL
);

CREATE TABLE service_change_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id  VARCHAR(30)  NOT NULL,
    change_type VARCHAR(20)  NOT NULL,
    field_name  VARCHAR(100),
    old_value   VARCHAR(4000),
    new_value   VARCHAR(4000),
    changed_at  TIMESTAMP    NOT NULL
);

CREATE TABLE public_service_reservations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id      VARCHAR(30)  NOT NULL,
    service_name    VARCHAR(200),
    service_status  VARCHAR(20),
    area_name       VARCHAR(50),
    max_class_name  VARCHAR(50),
    deleted_at      TIMESTAMP
);
