/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>public_service_reservations</code>.
     */
    public final PublicServiceReservations PUBLIC_SERVICE_RESERVATIONS = PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS;

    /**
     * The table <code>service_change_log</code>.
     */
    public final ServiceChangeLog SERVICE_CHANGE_LOG = ServiceChangeLog.SERVICE_CHANGE_LOG;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS,
            ServiceChangeLog.SERVICE_CHANGE_LOG,
            Users.USERS
        );
    }
}
