/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_PSR_AREA_NAME = Internal.createIndex(DSL.name("idx_psr_area_name"), PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, new OrderField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.AREA_NAME }, false);
    public static final Index IDX_PSR_MAX_CLASS_NAME = Internal.createIndex(DSL.name("idx_psr_max_class_name"), PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, new OrderField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.MAX_CLASS_NAME }, false);
    public static final Index IDX_PSR_RECEIPT_END_DT = Internal.createIndex(DSL.name("idx_psr_receipt_end_dt"), PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, new OrderField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.RECEIPT_END_DT }, false);
    public static final Index IDX_PSR_SERVICE_STATUS = Internal.createIndex(DSL.name("idx_psr_service_status"), PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, new OrderField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.SERVICE_STATUS }, false);
    public static final Index IDX_SCL_COLLECTION = Internal.createIndex(DSL.name("idx_scl_collection"), ServiceChangeLog.SERVICE_CHANGE_LOG, new OrderField[] { ServiceChangeLog.SERVICE_CHANGE_LOG.COLLECTION_ID }, false);
    public static final Index IDX_SCL_FIELD_NAME = Internal.createIndex(DSL.name("idx_scl_field_name"), ServiceChangeLog.SERVICE_CHANGE_LOG, new OrderField[] { ServiceChangeLog.SERVICE_CHANGE_LOG.FIELD_NAME, ServiceChangeLog.SERVICE_CHANGE_LOG.CHANGED_AT.desc() }, false);
    public static final Index IDX_SCL_SERVICE_ID = Internal.createIndex(DSL.name("idx_scl_service_id"), ServiceChangeLog.SERVICE_CHANGE_LOG, new OrderField[] { ServiceChangeLog.SERVICE_CHANGE_LOG.SERVICE_ID, ServiceChangeLog.SERVICE_CHANGE_LOG.CHANGED_AT.desc() }, false);
    public static final Index IDX_USERS_EMAIL_HASH = Internal.createIndex(DSL.name("idx_users_email_hash"), Users.USERS, new OrderField[] { Users.USERS.EMAIL_HASH }, false);
    public static final Index IDX_USERS_PHONE_HASH = Internal.createIndex(DSL.name("idx_users_phone_hash"), Users.USERS, new OrderField[] { Users.USERS.PHONE_HASH }, false);
}
