/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;
import dev.jazzybyte.onseoul.jooq.tables.records.PublicServiceReservationsRecord;
import dev.jazzybyte.onseoul.jooq.tables.records.ServiceChangeLogRecord;
import dev.jazzybyte.onseoul.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PublicServiceReservationsRecord> CONSTRAINT_7 = Internal.createUniqueKey(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, DSL.name("CONSTRAINT_7"), new TableField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.ID }, true);
    public static final UniqueKey<PublicServiceReservationsRecord> CONSTRAINT_7C = Internal.createUniqueKey(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, DSL.name("CONSTRAINT_7C"), new TableField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.SERVICE_ID }, true);
    public static final UniqueKey<ServiceChangeLogRecord> CONSTRAINT_A = Internal.createUniqueKey(ServiceChangeLog.SERVICE_CHANGE_LOG, DSL.name("CONSTRAINT_A"), new TableField[] { ServiceChangeLog.SERVICE_CHANGE_LOG.ID }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_6 = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_6"), new TableField[] { Users.USERS.ID }, true);
}
