/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;
import dev.jazzybyte.onseoul.jooq.tables.records.PublicServiceReservationsRecord;
import dev.jazzybyte.onseoul.jooq.tables.records.ServiceChangeLogRecord;
import dev.jazzybyte.onseoul.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PublicServiceReservationsRecord> PUBLIC_SERVICE_RESERVATIONS_PKEY = Internal.createUniqueKey(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, DSL.name("public_service_reservations_pkey"), new TableField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.ID }, true);
    public static final UniqueKey<PublicServiceReservationsRecord> PUBLIC_SERVICE_RESERVATIONS_SERVICE_ID_KEY = Internal.createUniqueKey(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS, DSL.name("public_service_reservations_service_id_key"), new TableField[] { PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS.SERVICE_ID }, true);
    public static final UniqueKey<ServiceChangeLogRecord> SERVICE_CHANGE_LOG_PKEY = Internal.createUniqueKey(ServiceChangeLog.SERVICE_CHANGE_LOG, DSL.name("service_change_log_pkey"), new TableField[] { ServiceChangeLog.SERVICE_CHANGE_LOG.ID }, true);
    public static final UniqueKey<UsersRecord> UQ_USERS_EMAIL_HASH = Internal.createUniqueKey(Users.USERS, DSL.name("uq_users_email_hash"), new TableField[] { Users.USERS.EMAIL_HASH }, true);
    public static final UniqueKey<UsersRecord> UQ_USERS_PROVIDER = Internal.createUniqueKey(Users.USERS, DSL.name("uq_users_provider"), new TableField[] { Users.USERS.PROVIDER, Users.USERS.PROVIDER_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
}
