/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.public_service_reservations</code>.
     */
    public final PublicServiceReservations PUBLIC_SERVICE_RESERVATIONS = PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS;

    /**
     * 공공서비스 수집 시 감지된 변경 이력. 추적 대상 필드(service_status, service_name, place_name,
     * receipt_start_dt, receipt_end_dt)의 변경만 기록한다.
     */
    public final ServiceChangeLog SERVICE_CHANGE_LOG = ServiceChangeLog.SERVICE_CHANGE_LOG;

    /**
     * OAuth2 소셜 로그인 사용자. 비밀번호 없음 — 인증은 외부 제공자에 위임
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS,
            ServiceChangeLog.SERVICE_CHANGE_LOG,
            Users.USERS
        );
    }
}
