/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.public_service_reservations</code>.
     */
    public static final PublicServiceReservations PUBLIC_SERVICE_RESERVATIONS = PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS;

    /**
     * 공공서비스 수집 시 감지된 변경 이력. 추적 대상 필드(service_status, service_name, place_name,
     * receipt_start_dt, receipt_end_dt)의 변경만 기록한다.
     */
    public static final ServiceChangeLog SERVICE_CHANGE_LOG = ServiceChangeLog.SERVICE_CHANGE_LOG;

    /**
     * OAuth2 소셜 로그인 사용자. 비밀번호 없음 — 인증은 외부 제공자에 위임
     */
    public static final Users USERS = Users.USERS;
}
