/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;
import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;
import dev.jazzybyte.onseoul.jooq.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public_service_reservations</code>.
     */
    public static final PublicServiceReservations PUBLIC_SERVICE_RESERVATIONS = PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS;

    /**
     * The table <code>service_change_log</code>.
     */
    public static final ServiceChangeLog SERVICE_CHANGE_LOG = ServiceChangeLog.SERVICE_CHANGE_LOG;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
