CREATE SEQUENCE IF NOT EXISTS chat_message_seq START WITH 1 INCREMENT BY 1;

-- ── service_change_log (H2 — notification module test) ──────
CREATE TABLE IF NOT EXISTS service_change_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id  BIGINT       NOT NULL DEFAULT 0,    -- prod: FK, H2: DEFAULT 0 허용
    service_id     VARCHAR(30)  NOT NULL,
    change_type    VARCHAR(20)  NOT NULL,
    field_name     VARCHAR(100),
    old_value      TEXT,
    new_value      TEXT,
    changed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── public_service_reservations (H2 — notification module test, JOIN 대상) ──
-- loadFiltered가 service_change_log JOIN public_service_reservations를 수행하므로
-- 필요한 필터 컬럼(service_status, area_name, max_class_name, deleted_at)만 포함한다.
CREATE TABLE IF NOT EXISTS public_service_reservations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id       VARCHAR(30)  NOT NULL UNIQUE,
    service_name     VARCHAR(200),
    place_name       VARCHAR(200),
    service_status   VARCHAR(20),
    area_name        VARCHAR(50),
    max_class_name   VARCHAR(50),
    service_url      TEXT,
    image_url        TEXT,
    target_info      VARCHAR(200),
    receipt_start_dt TIMESTAMP WITH TIME ZONE,
    receipt_end_dt   TIMESTAMP WITH TIME ZONE,
    deleted_at       TIMESTAMP WITH TIME ZONE
);

-- ── notification_subscriptions (H2) ──────────────────────────
CREATE TABLE IF NOT EXISTS notification_subscriptions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    filter           VARCHAR(2000) NOT NULL DEFAULT '{}',
    channels         VARCHAR(500)  NOT NULL DEFAULT '["EMAIL"]', -- H2는 jsonb_array_length 미지원으로 CHECK(jsonb_array_length > 0) 생략
    last_notified_at TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW()
    -- serviceId pin 제거: 구독 중복 방지 제약(uq_ns_user_service) 없음 — 조건 기반 다중 구독 허용
);

-- ── notification_batch (H2) ──────────────────────────────────
-- 스케줄러 실행 단위. ADR-0004 per-batch 모델.
CREATE TABLE IF NOT EXISTS notification_batch
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    finished_at  TIMESTAMP,
    status       VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    sent_count   INT,
    failed_count INT,

    CONSTRAINT chk_nb_status CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED'))
);

-- ── notification_dispatches (H2) ─────────────────────────────
-- ADR-0004: change_log_id 제거. batch_id, attempt_count 추가.
CREATE TABLE IF NOT EXISTS notification_dispatches
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT        NOT NULL REFERENCES notification_batch (id),
    subscription_id  BIGINT        NOT NULL REFERENCES notification_subscriptions (id),
    status           VARCHAR(10)   NOT NULL DEFAULT 'PENDING',
    sent_at          TIMESTAMP,
    generated_title  VARCHAR(200),
    generated_body   CLOB,
    template_source  VARCHAR(10),
    last_error       CLOB,
    attempt_count    INT           NOT NULL DEFAULT 0,
    -- JSONB in PostgreSQL; H2 test schema declares as VARCHAR (filter/channels와 동일 패턴).
    -- @JdbcTypeCode(SqlTypes.JSON) String 바인딩과 호환. NULL 허용.
    notification_payload VARCHAR(8000),
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_nd_batch_subscription UNIQUE (batch_id, subscription_id),
    CONSTRAINT chk_nd_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'DEAD')),
    CONSTRAINT chk_nd_template_source CHECK (template_source IN ('AI', 'FALLBACK') OR template_source IS NULL)
);
