-- ──────────────────────────────────────────────────────────────────
-- Testcontainers PostgreSQL 스키마 (M2 — cross-dedup JSONB containment IT).
-- migration 09/11/12 의 notification_dispatches 컬럼/인덱스를 PG 네이티브 형태로 재현한다.
-- H2 테스트 스키마와 달리:
--   - notification_payload 는 실제 JSONB 타입 (payload->'services' @> CAST(? AS jsonb) 평가용)
--   - uq_nd_scheduled_dedup / idx_nd_change_crossdedup 는 부분 인덱스(WHERE 술어 포함)
-- 이 IT 는 cross-dedup 선조회 쿼리(existsChangeDispatchCoveringService)만 검증하므로
-- 필요한 컬럼/제약/인덱스만 포함한다(batch/subscription FK 는 IT 단순화를 위해 생략).
-- ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS notification_dispatches
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id             BIGINT       NOT NULL,
    subscription_id      BIGINT       NOT NULL,
    trigger_type         VARCHAR(20)  NOT NULL DEFAULT 'CHANGE',
    dispatch_date        DATE,
    service_id           VARCHAR(30),
    status               VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    sent_at              TIMESTAMP,
    generated_title      VARCHAR(200),
    generated_body       TEXT,
    template_source      VARCHAR(10),
    last_error           TEXT,
    attempt_count        INT          NOT NULL DEFAULT 0,
    notification_payload JSONB,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_nd_batch_subscription UNIQUE (batch_id, subscription_id),
    CONSTRAINT chk_nd_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'DEAD', 'EXPIRED')),
    CONSTRAINT chk_nd_trigger_type CHECK (trigger_type IN ('CHANGE', 'OPEN_DAY', 'BEFORE_RECEIPT_D1', 'DEADLINE_DDAY')),
    CONSTRAINT chk_nd_template_source CHECK (template_source IN ('AI', 'FALLBACK') OR template_source IS NULL)
);

-- migration 11: 시점 트리거 service_id 단위 하루 1건 dedup (부분 unique 인덱스).
CREATE UNIQUE INDEX IF NOT EXISTS uq_nd_scheduled_dedup
    ON notification_dispatches (subscription_id, service_id, dispatch_date)
    WHERE service_id IS NOT NULL;

-- migration 12: CHANGE↔시점 cross-trigger dedup 선조회 가속 (부분 B-tree).
CREATE INDEX IF NOT EXISTS idx_nd_change_crossdedup
    ON notification_dispatches (subscription_id, dispatch_date)
    WHERE trigger_type = 'CHANGE';
