-- H2 users 테이블 (notification BC의 UserContactPersistenceAdapter 테스트 전용)
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(20)  NOT NULL,
    provider_id VARCHAR(100) NOT NULL,
    email_enc   TEXT,
    email_hash  VARCHAR(64),
    phone_enc   TEXT,
    phone_hash  VARCHAR(64),
    nickname    VARCHAR(100),
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_email_hash UNIQUE (email_hash)
);
