/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables;


import dev.jazzybyte.onseoul.jooq.Indexes;
import dev.jazzybyte.onseoul.jooq.Keys;
import dev.jazzybyte.onseoul.jooq.Public;
import dev.jazzybyte.onseoul.jooq.tables.records.PublicServiceReservationsRecord;

import java.math.BigDecimal;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PublicServiceReservations extends TableImpl<PublicServiceReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.public_service_reservations</code>
     */
    public static final PublicServiceReservations PUBLIC_SERVICE_RESERVATIONS = new PublicServiceReservations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PublicServiceReservationsRecord> getRecordType() {
        return PublicServiceReservationsRecord.class;
    }

    /**
     * The column <code>public.public_service_reservations.id</code>.
     */
    public final TableField<PublicServiceReservationsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.public_service_reservations.service_id</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.public_service_reservations.service_gubun</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_GUBUN = createField(DSL.name("service_gubun"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.max_class_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> MAX_CLASS_NAME = createField(DSL.name("max_class_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.min_class_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> MIN_CLASS_NAME = createField(DSL.name("min_class_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.public_service_reservations.service_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_NAME = createField(DSL.name("service_name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.service_status</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_STATUS = createField(DSL.name("service_status"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.prev_service_status</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> PREV_SERVICE_STATUS = createField(DSL.name("prev_service_status"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.public_service_reservations.payment_type</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> PAYMENT_TYPE = createField(DSL.name("payment_type"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.public_service_reservations.target_info</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> TARGET_INFO = createField(DSL.name("target_info"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.public_service_reservations.service_url</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_URL = createField(DSL.name("service_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.public_service_reservations.image_url</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.public_service_reservations.detail_content</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> DETAIL_CONTENT = createField(DSL.name("detail_content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.public_service_reservations.tel_no</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> TEL_NO = createField(DSL.name("tel_no"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.public_service_reservations.place_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> PLACE_NAME = createField(DSL.name("place_name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.public_service_reservations.area_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> AREA_NAME = createField(DSL.name("area_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.public_service_reservations.coord_x</code>.
     */
    public final TableField<PublicServiceReservationsRecord, BigDecimal> COORD_X = createField(DSL.name("coord_x"), SQLDataType.NUMERIC(20, 15), this, "");

    /**
     * The column <code>public.public_service_reservations.coord_y</code>.
     */
    public final TableField<PublicServiceReservationsRecord, BigDecimal> COORD_Y = createField(DSL.name("coord_y"), SQLDataType.NUMERIC(20, 15), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.service_open_start_dt</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> SERVICE_OPEN_START_DT = createField(DSL.name("service_open_start_dt"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.service_open_end_dt</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> SERVICE_OPEN_END_DT = createField(DSL.name("service_open_end_dt"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.receipt_start_dt</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> RECEIPT_START_DT = createField(DSL.name("receipt_start_dt"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.receipt_end_dt</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> RECEIPT_END_DT = createField(DSL.name("receipt_end_dt"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.use_time_start</code>.
     */
    public final TableField<PublicServiceReservationsRecord, LocalTime> USE_TIME_START = createField(DSL.name("use_time_start"), SQLDataType.LOCALTIME(6), this, "");

    /**
     * The column <code>public.public_service_reservations.use_time_end</code>.
     */
    public final TableField<PublicServiceReservationsRecord, LocalTime> USE_TIME_END = createField(DSL.name("use_time_end"), SQLDataType.LOCALTIME(6), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.cancel_std_type</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> CANCEL_STD_TYPE = createField(DSL.name("cancel_std_type"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.cancel_std_days</code>.
     */
    public final TableField<PublicServiceReservationsRecord, Short> CANCEL_STD_DAYS = createField(DSL.name("cancel_std_days"), SQLDataType.SMALLINT, this, "");

    /**
     * The column
     * <code>public.public_service_reservations.first_collected_at</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> FIRST_COLLECTED_AT = createField(DSL.name("first_collected_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column
     * <code>public.public_service_reservations.last_synced_at</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> LAST_SYNCED_AT = createField(DSL.name("last_synced_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.public_service_reservations.deleted_at</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PublicServiceReservations(Name alias, Table<PublicServiceReservationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PublicServiceReservations(Name alias, Table<PublicServiceReservationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.public_service_reservations</code> table
     * reference
     */
    public PublicServiceReservations(String alias) {
        this(DSL.name(alias), PUBLIC_SERVICE_RESERVATIONS);
    }

    /**
     * Create an aliased <code>public.public_service_reservations</code> table
     * reference
     */
    public PublicServiceReservations(Name alias) {
        this(alias, PUBLIC_SERVICE_RESERVATIONS);
    }

    /**
     * Create a <code>public.public_service_reservations</code> table reference
     */
    public PublicServiceReservations() {
        this(DSL.name("public_service_reservations"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PSR_AREA_NAME, Indexes.IDX_PSR_MAX_CLASS_NAME, Indexes.IDX_PSR_RECEIPT_END_DT, Indexes.IDX_PSR_SERVICE_STATUS);
    }

    @Override
    public Identity<PublicServiceReservationsRecord, Long> getIdentity() {
        return (Identity<PublicServiceReservationsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PublicServiceReservationsRecord> getPrimaryKey() {
        return Keys.PUBLIC_SERVICE_RESERVATIONS_PKEY;
    }

    @Override
    public List<UniqueKey<PublicServiceReservationsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PUBLIC_SERVICE_RESERVATIONS_SERVICE_ID_KEY);
    }

    @Override
    public PublicServiceReservations as(String alias) {
        return new PublicServiceReservations(DSL.name(alias), this);
    }

    @Override
    public PublicServiceReservations as(Name alias) {
        return new PublicServiceReservations(alias, this);
    }

    @Override
    public PublicServiceReservations as(Table<?> alias) {
        return new PublicServiceReservations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicServiceReservations rename(String name) {
        return new PublicServiceReservations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicServiceReservations rename(Name name) {
        return new PublicServiceReservations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicServiceReservations rename(Table<?> name) {
        return new PublicServiceReservations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Condition condition) {
        return new PublicServiceReservations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
