/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables;


import dev.jazzybyte.onseoul.jooq.DefaultSchema;
import dev.jazzybyte.onseoul.jooq.Keys;
import dev.jazzybyte.onseoul.jooq.tables.records.PublicServiceReservationsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PublicServiceReservations extends TableImpl<PublicServiceReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public_service_reservations</code>
     */
    public static final PublicServiceReservations PUBLIC_SERVICE_RESERVATIONS = new PublicServiceReservations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PublicServiceReservationsRecord> getRecordType() {
        return PublicServiceReservationsRecord.class;
    }

    /**
     * The column <code>public_service_reservations.id</code>.
     */
    public final TableField<PublicServiceReservationsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public_service_reservations.service_id</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public_service_reservations.service_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_NAME = createField(DSL.name("service_name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public_service_reservations.service_status</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> SERVICE_STATUS = createField(DSL.name("service_status"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public_service_reservations.area_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> AREA_NAME = createField(DSL.name("area_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public_service_reservations.max_class_name</code>.
     */
    public final TableField<PublicServiceReservationsRecord, String> MAX_CLASS_NAME = createField(DSL.name("max_class_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public_service_reservations.deleted_at</code>.
     */
    public final TableField<PublicServiceReservationsRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PublicServiceReservations(Name alias, Table<PublicServiceReservationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PublicServiceReservations(Name alias, Table<PublicServiceReservationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public_service_reservations</code> table
     * reference
     */
    public PublicServiceReservations(String alias) {
        this(DSL.name(alias), PUBLIC_SERVICE_RESERVATIONS);
    }

    /**
     * Create an aliased <code>public_service_reservations</code> table
     * reference
     */
    public PublicServiceReservations(Name alias) {
        this(alias, PUBLIC_SERVICE_RESERVATIONS);
    }

    /**
     * Create a <code>public_service_reservations</code> table reference
     */
    public PublicServiceReservations() {
        this(DSL.name("public_service_reservations"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<PublicServiceReservationsRecord, Long> getIdentity() {
        return (Identity<PublicServiceReservationsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PublicServiceReservationsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    @Override
    public List<UniqueKey<PublicServiceReservationsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_7C);
    }

    @Override
    public PublicServiceReservations as(String alias) {
        return new PublicServiceReservations(DSL.name(alias), this);
    }

    @Override
    public PublicServiceReservations as(Name alias) {
        return new PublicServiceReservations(alias, this);
    }

    @Override
    public PublicServiceReservations as(Table<?> alias) {
        return new PublicServiceReservations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicServiceReservations rename(String name) {
        return new PublicServiceReservations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicServiceReservations rename(Name name) {
        return new PublicServiceReservations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicServiceReservations rename(Table<?> name) {
        return new PublicServiceReservations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Condition condition) {
        return new PublicServiceReservations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PublicServiceReservations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PublicServiceReservations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
