/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables;


import dev.jazzybyte.onseoul.jooq.Indexes;
import dev.jazzybyte.onseoul.jooq.Keys;
import dev.jazzybyte.onseoul.jooq.Public;
import dev.jazzybyte.onseoul.jooq.tables.records.ServiceChangeLogRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 공공서비스 수집 시 감지된 변경 이력. 추적 대상 필드(service_status, service_name, place_name,
 * receipt_start_dt, receipt_end_dt)의 변경만 기록한다.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServiceChangeLog extends TableImpl<ServiceChangeLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.service_change_log</code>
     */
    public static final ServiceChangeLog SERVICE_CHANGE_LOG = new ServiceChangeLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceChangeLogRecord> getRecordType() {
        return ServiceChangeLogRecord.class;
    }

    /**
     * The column <code>public.service_change_log.id</code>. 내부 식별자
     */
    public final TableField<ServiceChangeLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "내부 식별자");

    /**
     * The column <code>public.service_change_log.service_id</code>. 변경된 서비스 ID
     * (public_service_reservations.service_id 논리 참조)
     */
    public final TableField<ServiceChangeLogRecord, String> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.VARCHAR(30).nullable(false), this, "변경된 서비스 ID (public_service_reservations.service_id 논리 참조)");

    /**
     * The column <code>public.service_change_log.collection_id</code>. 이 변경을
     * 감지한 수집 실행 ID (collection_history.id 논리 참조)
     */
    public final TableField<ServiceChangeLogRecord, Long> COLLECTION_ID = createField(DSL.name("collection_id"), SQLDataType.BIGINT.nullable(false), this, "이 변경을 감지한 수집 실행 ID (collection_history.id 논리 참조)");

    /**
     * The column <code>public.service_change_log.change_type</code>. 변경 유형.
     * NEW: 신규 등록 / UPDATED: 필드 변경 / DELETED: 삭제(soft delete 처리됨)
     */
    public final TableField<ServiceChangeLogRecord, String> CHANGE_TYPE = createField(DSL.name("change_type"), SQLDataType.VARCHAR(10).nullable(false), this, "변경 유형. NEW: 신규 등록 / UPDATED: 필드 변경 / DELETED: 삭제(soft delete 처리됨)");

    /**
     * The column <code>public.service_change_log.field_name</code>. 변경된 필드명.
     * change_type = UPDATED 일 때만 값이 존재하며 NEW/DELETED 는 NULL
     */
    public final TableField<ServiceChangeLogRecord, String> FIELD_NAME = createField(DSL.name("field_name"), SQLDataType.VARCHAR(50), this, "변경된 필드명. change_type = UPDATED 일 때만 값이 존재하며 NEW/DELETED 는 NULL");

    /**
     * The column <code>public.service_change_log.old_value</code>. 변경 전 값.
     * change_type = NEW 이면 NULL
     */
    public final TableField<ServiceChangeLogRecord, String> OLD_VALUE = createField(DSL.name("old_value"), SQLDataType.CLOB, this, "변경 전 값. change_type = NEW 이면 NULL");

    /**
     * The column <code>public.service_change_log.new_value</code>. 변경 후 값.
     * change_type = DELETED 이면 NULL
     */
    public final TableField<ServiceChangeLogRecord, String> NEW_VALUE = createField(DSL.name("new_value"), SQLDataType.CLOB, this, "변경 후 값. change_type = DELETED 이면 NULL");

    /**
     * The column <code>public.service_change_log.changed_at</code>. 변경 감지 시각
     * (수집 파이프라인 실행 시각 기준)
     */
    public final TableField<ServiceChangeLogRecord, OffsetDateTime> CHANGED_AT = createField(DSL.name("changed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "변경 감지 시각 (수집 파이프라인 실행 시각 기준)");

    private ServiceChangeLog(Name alias, Table<ServiceChangeLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServiceChangeLog(Name alias, Table<ServiceChangeLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("공공서비스 수집 시 감지된 변경 이력. 추적 대상 필드(service_status, service_name, place_name, receipt_start_dt, receipt_end_dt)의 변경만 기록한다."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.service_change_log</code> table reference
     */
    public ServiceChangeLog(String alias) {
        this(DSL.name(alias), SERVICE_CHANGE_LOG);
    }

    /**
     * Create an aliased <code>public.service_change_log</code> table reference
     */
    public ServiceChangeLog(Name alias) {
        this(alias, SERVICE_CHANGE_LOG);
    }

    /**
     * Create a <code>public.service_change_log</code> table reference
     */
    public ServiceChangeLog() {
        this(DSL.name("service_change_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SCL_COLLECTION, Indexes.IDX_SCL_FIELD_NAME, Indexes.IDX_SCL_SERVICE_ID);
    }

    @Override
    public Identity<ServiceChangeLogRecord, Long> getIdentity() {
        return (Identity<ServiceChangeLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServiceChangeLogRecord> getPrimaryKey() {
        return Keys.SERVICE_CHANGE_LOG_PKEY;
    }

    @Override
    public ServiceChangeLog as(String alias) {
        return new ServiceChangeLog(DSL.name(alias), this);
    }

    @Override
    public ServiceChangeLog as(Name alias) {
        return new ServiceChangeLog(alias, this);
    }

    @Override
    public ServiceChangeLog as(Table<?> alias) {
        return new ServiceChangeLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceChangeLog rename(String name) {
        return new ServiceChangeLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceChangeLog rename(Name name) {
        return new ServiceChangeLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceChangeLog rename(Table<?> name) {
        return new ServiceChangeLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Condition condition) {
        return new ServiceChangeLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
