/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables;


import dev.jazzybyte.onseoul.jooq.DefaultSchema;
import dev.jazzybyte.onseoul.jooq.Keys;
import dev.jazzybyte.onseoul.jooq.tables.records.ServiceChangeLogRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServiceChangeLog extends TableImpl<ServiceChangeLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>service_change_log</code>
     */
    public static final ServiceChangeLog SERVICE_CHANGE_LOG = new ServiceChangeLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceChangeLogRecord> getRecordType() {
        return ServiceChangeLogRecord.class;
    }

    /**
     * The column <code>service_change_log.id</code>.
     */
    public final TableField<ServiceChangeLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>service_change_log.collection_id</code>.
     */
    public final TableField<ServiceChangeLogRecord, Long> COLLECTION_ID = createField(DSL.name("collection_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>service_change_log.service_id</code>.
     */
    public final TableField<ServiceChangeLogRecord, String> SERVICE_ID = createField(DSL.name("service_id"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>service_change_log.change_type</code>.
     */
    public final TableField<ServiceChangeLogRecord, String> CHANGE_TYPE = createField(DSL.name("change_type"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>service_change_log.field_name</code>.
     */
    public final TableField<ServiceChangeLogRecord, String> FIELD_NAME = createField(DSL.name("field_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>service_change_log.old_value</code>.
     */
    public final TableField<ServiceChangeLogRecord, String> OLD_VALUE = createField(DSL.name("old_value"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>service_change_log.new_value</code>.
     */
    public final TableField<ServiceChangeLogRecord, String> NEW_VALUE = createField(DSL.name("new_value"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>service_change_log.changed_at</code>.
     */
    public final TableField<ServiceChangeLogRecord, OffsetDateTime> CHANGED_AT = createField(DSL.name("changed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ServiceChangeLog(Name alias, Table<ServiceChangeLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServiceChangeLog(Name alias, Table<ServiceChangeLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>service_change_log</code> table reference
     */
    public ServiceChangeLog(String alias) {
        this(DSL.name(alias), SERVICE_CHANGE_LOG);
    }

    /**
     * Create an aliased <code>service_change_log</code> table reference
     */
    public ServiceChangeLog(Name alias) {
        this(alias, SERVICE_CHANGE_LOG);
    }

    /**
     * Create a <code>service_change_log</code> table reference
     */
    public ServiceChangeLog() {
        this(DSL.name("service_change_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ServiceChangeLogRecord, Long> getIdentity() {
        return (Identity<ServiceChangeLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServiceChangeLogRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    @Override
    public ServiceChangeLog as(String alias) {
        return new ServiceChangeLog(DSL.name(alias), this);
    }

    @Override
    public ServiceChangeLog as(Name alias) {
        return new ServiceChangeLog(alias, this);
    }

    @Override
    public ServiceChangeLog as(Table<?> alias) {
        return new ServiceChangeLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceChangeLog rename(String name) {
        return new ServiceChangeLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceChangeLog rename(Name name) {
        return new ServiceChangeLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceChangeLog rename(Table<?> name) {
        return new ServiceChangeLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Condition condition) {
        return new ServiceChangeLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServiceChangeLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServiceChangeLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
