/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables;


import dev.jazzybyte.onseoul.jooq.Indexes;
import dev.jazzybyte.onseoul.jooq.Keys;
import dev.jazzybyte.onseoul.jooq.Public;
import dev.jazzybyte.onseoul.jooq.tables.records.UsersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * OAuth2 소셜 로그인 사용자. 비밀번호 없음 — 인증은 외부 제공자에 위임
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>public.users.id</code>.
     */
    public final TableField<UsersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.users.provider</code>. OAuth2 제공자 식별자 (google,
     * kakao, github 등)
     */
    public final TableField<UsersRecord, String> PROVIDER = createField(DSL.name("provider"), SQLDataType.VARCHAR(20).nullable(false), this, "OAuth2 제공자 식별자 (google, kakao, github 등)");

    /**
     * The column <code>public.users.provider_id</code>. 제공자가 발급한 사용자 고유 ID
     */
    public final TableField<UsersRecord, String> PROVIDER_ID = createField(DSL.name("provider_id"), SQLDataType.VARCHAR(100).nullable(false), this, "제공자가 발급한 사용자 고유 ID");

    /**
     * The column <code>public.users.nickname</code>.
     */
    public final TableField<UsersRecord, String> NICKNAME = createField(DSL.name("nickname"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.users.status</code>. 계정 상태. ACTIVE: 정상 /
     * SUSPENDED: 이용 정지 / DELETED: 탈퇴(소프트)
     */
    public final TableField<UsersRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "계정 상태. ACTIVE: 정상 / SUSPENDED: 이용 정지 / DELETED: 탈퇴(소프트)");

    /**
     * The column <code>public.users.created_at</code>.
     */
    public final TableField<UsersRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.users.updated_at</code>.
     */
    public final TableField<UsersRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.users.email_enc</code>. AES-256-GCM 암호화된 이메일. 형식:
     * v1:&lt;base64(iv||tag||ciphertext)&gt;. 복호화는 앱 레이어에서만 수행
     */
    public final TableField<UsersRecord, String> EMAIL_ENC = createField(DSL.name("email_enc"), SQLDataType.CLOB, this, "AES-256-GCM 암호화된 이메일. 형식: v1:<base64(iv||tag||ciphertext)>. 복호화는 앱 레이어에서만 수행");

    /**
     * The column <code>public.users.phone_enc</code>. AES-256-GCM 암호화된 전화번호.
     * 형식: v1:&lt;base64(iv||tag||ciphertext)&gt;. 복호화는 앱 레이어에서만 수행
     */
    public final TableField<UsersRecord, String> PHONE_ENC = createField(DSL.name("phone_enc"), SQLDataType.CLOB, this, "AES-256-GCM 암호화된 전화번호. 형식: v1:<base64(iv||tag||ciphertext)>. 복호화는 앱 레이어에서만 수행");

    /**
     * The column <code>public.users.email_hash</code>.
     * HMAC-SHA256(trim+lowercase(email), BLIND_IDX_KEY) hex. 중복 가입 체크 및 로그인 조회
     * 전용. UNIQUE 제약 적용 (null 제외)
     */
    public final TableField<UsersRecord, String> EMAIL_HASH = createField(DSL.name("email_hash"), SQLDataType.VARCHAR(64), this, "HMAC-SHA256(trim+lowercase(email), BLIND_IDX_KEY) hex. 중복 가입 체크 및 로그인 조회 전용. UNIQUE 제약 적용 (null 제외)");

    /**
     * The column <code>public.users.phone_hash</code>.
     * HMAC-SHA256(숫자만추출(phone), BLIND_IDX_KEY) hex. 전화번호 기반 조회 전용
     */
    public final TableField<UsersRecord, String> PHONE_HASH = createField(DSL.name("phone_hash"), SQLDataType.VARCHAR(64), this, "HMAC-SHA256(숫자만추출(phone), BLIND_IDX_KEY) hex. 전화번호 기반 조회 전용");

    private Users(Name alias, Table<UsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Users(Name alias, Table<UsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("OAuth2 소셜 로그인 사용자. 비밀번호 없음 — 인증은 외부 제공자에 위임"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    public Users(String alias) {
        this(DSL.name(alias), USERS);
    }

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    public Users(Name alias) {
        this(alias, USERS);
    }

    /**
     * Create a <code>public.users</code> table reference
     */
    public Users() {
        this(DSL.name("users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USERS_EMAIL_HASH, Indexes.IDX_USERS_PHONE_HASH);
    }

    @Override
    public Identity<UsersRecord, Long> getIdentity() {
        return (Identity<UsersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsersRecord> getPrimaryKey() {
        return Keys.USERS_PKEY;
    }

    @Override
    public List<UniqueKey<UsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_USERS_EMAIL_HASH, Keys.UQ_USERS_PROVIDER);
    }

    @Override
    public Users as(String alias) {
        return new Users(DSL.name(alias), this);
    }

    @Override
    public Users as(Name alias) {
        return new Users(alias, this);
    }

    @Override
    public Users as(Table<?> alias) {
        return new Users(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(String name) {
        return new Users(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Name name) {
        return new Users(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Table<?> name) {
        return new Users(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition condition) {
        return new Users(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
