-- H2 compatible schema for @DataJpaTest
-- Used when spring.jpa.hibernate.ddl-auto=none

CREATE SEQUENCE IF NOT EXISTS chat_message_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS chat_rooms (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    title           VARCHAR(500) NOT NULL,
    is_title_generated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT NOT NULL,
    seq         BIGINT NOT NULL,
    role        VARCHAR(20) NOT NULL,
    content     CLOB NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(20) NOT NULL,
    provider_id VARCHAR(100) NOT NULL,
    email       VARCHAR(255),
    nickname    VARCHAR(100),
    status      VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS api_source_catalog (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id       VARCHAR(20) NOT NULL UNIQUE,
    dataset_name     VARCHAR(100) NOT NULL,
    dataset_url      CLOB NOT NULL,
    api_service_path VARCHAR(100) NOT NULL,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    tags             VARCHAR(200),
    meta_updated_at  DATE,
    data_updated_at  TIMESTAMP,
    created_at       TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public_service_reservations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id            VARCHAR(30) NOT NULL UNIQUE,
    service_gubun         VARCHAR(20),
    max_class_name        VARCHAR(50),
    min_class_name        VARCHAR(50),
    service_name          VARCHAR(200) NOT NULL,
    service_status        VARCHAR(20) NOT NULL,
    prev_service_status   VARCHAR(20),
    payment_type          VARCHAR(50),
    target_info           VARCHAR(200),
    service_url           CLOB,
    image_url             CLOB,
    detail_content        CLOB,
    tel_no                VARCHAR(20),
    place_name            VARCHAR(200),
    area_name             VARCHAR(50),
    coord_x               DECIMAL(20, 15),
    coord_y               DECIMAL(20, 15),
    service_open_start_dt TIMESTAMP,
    service_open_end_dt   TIMESTAMP,
    receipt_start_dt      TIMESTAMP,
    receipt_end_dt        TIMESTAMP,
    use_time_start        TIME,
    use_time_end          TIME,
    cancel_std_type       VARCHAR(30),
    cancel_std_days       SMALLINT,
    first_collected_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    last_synced_at        TIMESTAMP NOT NULL,
    deleted_at            TIMESTAMP
);

CREATE TABLE IF NOT EXISTS collection_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      BIGINT NOT NULL,
    collected_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    status         VARCHAR(10) NOT NULL,
    total_fetched  INT NOT NULL DEFAULT 0,
    new_count      INT NOT NULL DEFAULT 0,
    updated_count  INT NOT NULL DEFAULT 0,
    deleted_count  INT NOT NULL DEFAULT 0,
    duration_ms    INT,
    error_message  CLOB
);

CREATE TABLE IF NOT EXISTS service_change_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id    VARCHAR(30) NOT NULL,
    collection_id BIGINT NOT NULL,
    change_type   VARCHAR(10) NOT NULL,
    field_name    VARCHAR(50),
    old_value     CLOB,
    new_value     CLOB,
    changed_at    TIMESTAMP NOT NULL DEFAULT NOW()
);
