/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables.records;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PublicServiceReservationsRecord extends UpdatableRecordImpl<PublicServiceReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public_service_reservations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public_service_reservations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public_service_reservations.service_id</code>.
     */
    public void setServiceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public_service_reservations.service_id</code>.
     */
    public String getServiceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public_service_reservations.service_name</code>.
     */
    public void setServiceName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public_service_reservations.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public_service_reservations.service_status</code>.
     */
    public void setServiceStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public_service_reservations.service_status</code>.
     */
    public String getServiceStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public_service_reservations.area_name</code>.
     */
    public void setAreaName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public_service_reservations.area_name</code>.
     */
    public String getAreaName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public_service_reservations.max_class_name</code>.
     */
    public void setMaxClassName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public_service_reservations.max_class_name</code>.
     */
    public String getMaxClassName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public_service_reservations.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public_service_reservations.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublicServiceReservationsRecord
     */
    public PublicServiceReservationsRecord() {
        super(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS);
    }

    /**
     * Create a detached, initialised PublicServiceReservationsRecord
     */
    public PublicServiceReservationsRecord(Long id, String serviceId, String serviceName, String serviceStatus, String areaName, String maxClassName, OffsetDateTime deletedAt) {
        super(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS);

        setId(id);
        setServiceId(serviceId);
        setServiceName(serviceName);
        setServiceStatus(serviceStatus);
        setAreaName(areaName);
        setMaxClassName(maxClassName);
        setDeletedAt(deletedAt);
        resetChangedOnNotNull();
    }
}
