/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables.records;


import dev.jazzybyte.onseoul.jooq.tables.PublicServiceReservations;

import java.math.BigDecimal;
import java.time.LocalTime;
import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PublicServiceReservationsRecord extends UpdatableRecordImpl<PublicServiceReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.public_service_reservations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.public_service_reservations.service_id</code>.
     */
    public void setServiceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.service_id</code>.
     */
    public String getServiceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.public_service_reservations.service_gubun</code>.
     */
    public void setServiceGubun(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.service_gubun</code>.
     */
    public String getServiceGubun() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.max_class_name</code>.
     */
    public void setMaxClassName(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.max_class_name</code>.
     */
    public String getMaxClassName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.min_class_name</code>.
     */
    public void setMinClassName(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.min_class_name</code>.
     */
    public String getMinClassName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.public_service_reservations.service_name</code>.
     */
    public void setServiceName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.service_status</code>.
     */
    public void setServiceStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.service_status</code>.
     */
    public String getServiceStatus() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.prev_service_status</code>.
     */
    public void setPrevServiceStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.prev_service_status</code>.
     */
    public String getPrevServiceStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.public_service_reservations.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.public_service_reservations.target_info</code>.
     */
    public void setTargetInfo(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.target_info</code>.
     */
    public String getTargetInfo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.public_service_reservations.service_url</code>.
     */
    public void setServiceUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.service_url</code>.
     */
    public String getServiceUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.public_service_reservations.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.detail_content</code>.
     */
    public void setDetailContent(String value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.detail_content</code>.
     */
    public String getDetailContent() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.public_service_reservations.tel_no</code>.
     */
    public void setTelNo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.tel_no</code>.
     */
    public String getTelNo() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.public_service_reservations.place_name</code>.
     */
    public void setPlaceName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.place_name</code>.
     */
    public String getPlaceName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.public_service_reservations.area_name</code>.
     */
    public void setAreaName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.area_name</code>.
     */
    public String getAreaName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.public_service_reservations.coord_x</code>.
     */
    public void setCoordX(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.coord_x</code>.
     */
    public BigDecimal getCoordX() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>public.public_service_reservations.coord_y</code>.
     */
    public void setCoordY(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.coord_y</code>.
     */
    public BigDecimal getCoordY() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.service_open_start_dt</code>.
     */
    public void setServiceOpenStartDt(OffsetDateTime value) {
        set(18, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.service_open_start_dt</code>.
     */
    public OffsetDateTime getServiceOpenStartDt() {
        return (OffsetDateTime) get(18);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.service_open_end_dt</code>.
     */
    public void setServiceOpenEndDt(OffsetDateTime value) {
        set(19, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.service_open_end_dt</code>.
     */
    public OffsetDateTime getServiceOpenEndDt() {
        return (OffsetDateTime) get(19);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.receipt_start_dt</code>.
     */
    public void setReceiptStartDt(OffsetDateTime value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.receipt_start_dt</code>.
     */
    public OffsetDateTime getReceiptStartDt() {
        return (OffsetDateTime) get(20);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.receipt_end_dt</code>.
     */
    public void setReceiptEndDt(OffsetDateTime value) {
        set(21, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.receipt_end_dt</code>.
     */
    public OffsetDateTime getReceiptEndDt() {
        return (OffsetDateTime) get(21);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.use_time_start</code>.
     */
    public void setUseTimeStart(LocalTime value) {
        set(22, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.use_time_start</code>.
     */
    public LocalTime getUseTimeStart() {
        return (LocalTime) get(22);
    }

    /**
     * Setter for <code>public.public_service_reservations.use_time_end</code>.
     */
    public void setUseTimeEnd(LocalTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.use_time_end</code>.
     */
    public LocalTime getUseTimeEnd() {
        return (LocalTime) get(23);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.cancel_std_type</code>.
     */
    public void setCancelStdType(String value) {
        set(24, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.cancel_std_type</code>.
     */
    public String getCancelStdType() {
        return (String) get(24);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.cancel_std_days</code>.
     */
    public void setCancelStdDays(Short value) {
        set(25, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.cancel_std_days</code>.
     */
    public Short getCancelStdDays() {
        return (Short) get(25);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.first_collected_at</code>.
     */
    public void setFirstCollectedAt(OffsetDateTime value) {
        set(26, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.first_collected_at</code>.
     */
    public OffsetDateTime getFirstCollectedAt() {
        return (OffsetDateTime) get(26);
    }

    /**
     * Setter for
     * <code>public.public_service_reservations.last_synced_at</code>.
     */
    public void setLastSyncedAt(OffsetDateTime value) {
        set(27, value);
    }

    /**
     * Getter for
     * <code>public.public_service_reservations.last_synced_at</code>.
     */
    public OffsetDateTime getLastSyncedAt() {
        return (OffsetDateTime) get(27);
    }

    /**
     * Setter for <code>public.public_service_reservations.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.public_service_reservations.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(28);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublicServiceReservationsRecord
     */
    public PublicServiceReservationsRecord() {
        super(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS);
    }

    /**
     * Create a detached, initialised PublicServiceReservationsRecord
     */
    public PublicServiceReservationsRecord(Long id, String serviceId, String serviceGubun, String maxClassName, String minClassName, String serviceName, String serviceStatus, String prevServiceStatus, String paymentType, String targetInfo, String serviceUrl, String imageUrl, String detailContent, String telNo, String placeName, String areaName, BigDecimal coordX, BigDecimal coordY, OffsetDateTime serviceOpenStartDt, OffsetDateTime serviceOpenEndDt, OffsetDateTime receiptStartDt, OffsetDateTime receiptEndDt, LocalTime useTimeStart, LocalTime useTimeEnd, String cancelStdType, Short cancelStdDays, OffsetDateTime firstCollectedAt, OffsetDateTime lastSyncedAt, OffsetDateTime deletedAt) {
        super(PublicServiceReservations.PUBLIC_SERVICE_RESERVATIONS);

        setId(id);
        setServiceId(serviceId);
        setServiceGubun(serviceGubun);
        setMaxClassName(maxClassName);
        setMinClassName(minClassName);
        setServiceName(serviceName);
        setServiceStatus(serviceStatus);
        setPrevServiceStatus(prevServiceStatus);
        setPaymentType(paymentType);
        setTargetInfo(targetInfo);
        setServiceUrl(serviceUrl);
        setImageUrl(imageUrl);
        setDetailContent(detailContent);
        setTelNo(telNo);
        setPlaceName(placeName);
        setAreaName(areaName);
        setCoordX(coordX);
        setCoordY(coordY);
        setServiceOpenStartDt(serviceOpenStartDt);
        setServiceOpenEndDt(serviceOpenEndDt);
        setReceiptStartDt(receiptStartDt);
        setReceiptEndDt(receiptEndDt);
        setUseTimeStart(useTimeStart);
        setUseTimeEnd(useTimeEnd);
        setCancelStdType(cancelStdType);
        setCancelStdDays(cancelStdDays);
        setFirstCollectedAt(firstCollectedAt);
        setLastSyncedAt(lastSyncedAt);
        setDeletedAt(deletedAt);
        resetChangedOnNotNull();
    }
}
