/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables.records;


import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 공공서비스 수집 시 감지된 변경 이력. 추적 대상 필드(service_status, service_name, place_name,
 * receipt_start_dt, receipt_end_dt)의 변경만 기록한다.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServiceChangeLogRecord extends UpdatableRecordImpl<ServiceChangeLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.service_change_log.id</code>. 내부 식별자
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.service_change_log.id</code>. 내부 식별자
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.service_change_log.service_id</code>. 변경된 서비스 ID
     * (public_service_reservations.service_id 논리 참조)
     */
    public void setServiceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.service_change_log.service_id</code>. 변경된 서비스 ID
     * (public_service_reservations.service_id 논리 참조)
     */
    public String getServiceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.service_change_log.collection_id</code>. 이 변경을
     * 감지한 수집 실행 ID (collection_history.id 논리 참조)
     */
    public void setCollectionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.service_change_log.collection_id</code>. 이 변경을
     * 감지한 수집 실행 ID (collection_history.id 논리 참조)
     */
    public Long getCollectionId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.service_change_log.change_type</code>. 변경 유형.
     * NEW: 신규 등록 / UPDATED: 필드 변경 / DELETED: 삭제(soft delete 처리됨)
     */
    public void setChangeType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.service_change_log.change_type</code>. 변경 유형.
     * NEW: 신규 등록 / UPDATED: 필드 변경 / DELETED: 삭제(soft delete 처리됨)
     */
    public String getChangeType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.service_change_log.field_name</code>. 변경된 필드명.
     * change_type = UPDATED 일 때만 값이 존재하며 NEW/DELETED 는 NULL
     */
    public void setFieldName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.service_change_log.field_name</code>. 변경된 필드명.
     * change_type = UPDATED 일 때만 값이 존재하며 NEW/DELETED 는 NULL
     */
    public String getFieldName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.service_change_log.old_value</code>. 변경 전 값.
     * change_type = NEW 이면 NULL
     */
    public void setOldValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.service_change_log.old_value</code>. 변경 전 값.
     * change_type = NEW 이면 NULL
     */
    public String getOldValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.service_change_log.new_value</code>. 변경 후 값.
     * change_type = DELETED 이면 NULL
     */
    public void setNewValue(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.service_change_log.new_value</code>. 변경 후 값.
     * change_type = DELETED 이면 NULL
     */
    public String getNewValue() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.service_change_log.changed_at</code>. 변경 감지 시각
     * (수집 파이프라인 실행 시각 기준)
     */
    public void setChangedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.service_change_log.changed_at</code>. 변경 감지 시각
     * (수집 파이프라인 실행 시각 기준)
     */
    public OffsetDateTime getChangedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceChangeLogRecord
     */
    public ServiceChangeLogRecord() {
        super(ServiceChangeLog.SERVICE_CHANGE_LOG);
    }

    /**
     * Create a detached, initialised ServiceChangeLogRecord
     */
    public ServiceChangeLogRecord(Long id, String serviceId, Long collectionId, String changeType, String fieldName, String oldValue, String newValue, OffsetDateTime changedAt) {
        super(ServiceChangeLog.SERVICE_CHANGE_LOG);

        setId(id);
        setServiceId(serviceId);
        setCollectionId(collectionId);
        setChangeType(changeType);
        setFieldName(fieldName);
        setOldValue(oldValue);
        setNewValue(newValue);
        setChangedAt(changedAt);
        resetChangedOnNotNull();
    }
}
