/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables.records;


import dev.jazzybyte.onseoul.jooq.tables.ServiceChangeLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServiceChangeLogRecord extends UpdatableRecordImpl<ServiceChangeLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>service_change_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>service_change_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>service_change_log.collection_id</code>.
     */
    public void setCollectionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>service_change_log.collection_id</code>.
     */
    public Long getCollectionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>service_change_log.service_id</code>.
     */
    public void setServiceId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>service_change_log.service_id</code>.
     */
    public String getServiceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>service_change_log.change_type</code>.
     */
    public void setChangeType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>service_change_log.change_type</code>.
     */
    public String getChangeType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>service_change_log.field_name</code>.
     */
    public void setFieldName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>service_change_log.field_name</code>.
     */
    public String getFieldName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>service_change_log.old_value</code>.
     */
    public void setOldValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>service_change_log.old_value</code>.
     */
    public String getOldValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>service_change_log.new_value</code>.
     */
    public void setNewValue(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>service_change_log.new_value</code>.
     */
    public String getNewValue() {
        return (String) get(6);
    }

    /**
     * Setter for <code>service_change_log.changed_at</code>.
     */
    public void setChangedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>service_change_log.changed_at</code>.
     */
    public OffsetDateTime getChangedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceChangeLogRecord
     */
    public ServiceChangeLogRecord() {
        super(ServiceChangeLog.SERVICE_CHANGE_LOG);
    }

    /**
     * Create a detached, initialised ServiceChangeLogRecord
     */
    public ServiceChangeLogRecord(Long id, Long collectionId, String serviceId, String changeType, String fieldName, String oldValue, String newValue, OffsetDateTime changedAt) {
        super(ServiceChangeLog.SERVICE_CHANGE_LOG);

        setId(id);
        setCollectionId(collectionId);
        setServiceId(serviceId);
        setChangeType(changeType);
        setFieldName(fieldName);
        setOldValue(oldValue);
        setNewValue(newValue);
        setChangedAt(changedAt);
        resetChangedOnNotNull();
    }
}
