/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables.records;


import dev.jazzybyte.onseoul.jooq.tables.Users;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * OAuth2 소셜 로그인 사용자. 비밀번호 없음 — 인증은 외부 제공자에 위임
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.provider</code>. OAuth2 제공자 식별자 (google,
     * kakao, github 등)
     */
    public void setProvider(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.provider</code>. OAuth2 제공자 식별자 (google,
     * kakao, github 등)
     */
    public String getProvider() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.provider_id</code>. 제공자가 발급한 사용자 고유 ID
     */
    public void setProviderId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.provider_id</code>. 제공자가 발급한 사용자 고유 ID
     */
    public String getProviderId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.nickname</code>.
     */
    public void setNickname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.nickname</code>.
     */
    public String getNickname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.status</code>. 계정 상태. ACTIVE: 정상 /
     * SUSPENDED: 이용 정지 / DELETED: 탈퇴(소프트)
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.status</code>. 계정 상태. ACTIVE: 정상 /
     * SUSPENDED: 이용 정지 / DELETED: 탈퇴(소프트)
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.users.email_enc</code>. AES-256-GCM 암호화된 이메일. 형식:
     * v1:&lt;base64(iv||tag||ciphertext)&gt;. 복호화는 앱 레이어에서만 수행
     */
    public void setEmailEnc(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.email_enc</code>. AES-256-GCM 암호화된 이메일. 형식:
     * v1:&lt;base64(iv||tag||ciphertext)&gt;. 복호화는 앱 레이어에서만 수행
     */
    public String getEmailEnc() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users.phone_enc</code>. AES-256-GCM 암호화된 전화번호.
     * 형식: v1:&lt;base64(iv||tag||ciphertext)&gt;. 복호화는 앱 레이어에서만 수행
     */
    public void setPhoneEnc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.phone_enc</code>. AES-256-GCM 암호화된 전화번호.
     * 형식: v1:&lt;base64(iv||tag||ciphertext)&gt;. 복호화는 앱 레이어에서만 수행
     */
    public String getPhoneEnc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.users.email_hash</code>.
     * HMAC-SHA256(trim+lowercase(email), BLIND_IDX_KEY) hex. 중복 가입 체크 및 로그인 조회
     * 전용. UNIQUE 제약 적용 (null 제외)
     */
    public void setEmailHash(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.email_hash</code>.
     * HMAC-SHA256(trim+lowercase(email), BLIND_IDX_KEY) hex. 중복 가입 체크 및 로그인 조회
     * 전용. UNIQUE 제약 적용 (null 제외)
     */
    public String getEmailHash() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.users.phone_hash</code>.
     * HMAC-SHA256(숫자만추출(phone), BLIND_IDX_KEY) hex. 전화번호 기반 조회 전용
     */
    public void setPhoneHash(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.users.phone_hash</code>.
     * HMAC-SHA256(숫자만추출(phone), BLIND_IDX_KEY) hex. 전화번호 기반 조회 전용
     */
    public String getPhoneHash() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, String provider, String providerId, String nickname, String status, OffsetDateTime createdAt, OffsetDateTime updatedAt, String emailEnc, String phoneEnc, String emailHash, String phoneHash) {
        super(Users.USERS);

        setId(id);
        setProvider(provider);
        setProviderId(providerId);
        setNickname(nickname);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setEmailEnc(emailEnc);
        setPhoneEnc(phoneEnc);
        setEmailHash(emailHash);
        setPhoneHash(phoneHash);
        resetChangedOnNotNull();
    }
}
