/*
 * This file is generated by jOOQ.
 */
package dev.jazzybyte.onseoul.jooq.tables.records;


import dev.jazzybyte.onseoul.jooq.tables.Users;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>users.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>users.provider</code>.
     */
    public void setProvider(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>users.provider</code>.
     */
    public String getProvider() {
        return (String) get(1);
    }

    /**
     * Setter for <code>users.provider_id</code>.
     */
    public void setProviderId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>users.provider_id</code>.
     */
    public String getProviderId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>users.email_enc</code>.
     */
    public void setEmailEnc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>users.email_enc</code>.
     */
    public String getEmailEnc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>users.email_hash</code>.
     */
    public void setEmailHash(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>users.email_hash</code>.
     */
    public String getEmailHash() {
        return (String) get(4);
    }

    /**
     * Setter for <code>users.phone_enc</code>.
     */
    public void setPhoneEnc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>users.phone_enc</code>.
     */
    public String getPhoneEnc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>users.phone_hash</code>.
     */
    public void setPhoneHash(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>users.phone_hash</code>.
     */
    public String getPhoneHash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>users.nickname</code>.
     */
    public void setNickname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>users.nickname</code>.
     */
    public String getNickname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>users.status</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>users.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>users.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>users.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>users.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>users.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, String provider, String providerId, String emailEnc, String emailHash, String phoneEnc, String phoneHash, String nickname, String status, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Users.USERS);

        setId(id);
        setProvider(provider);
        setProviderId(providerId);
        setEmailEnc(emailEnc);
        setEmailHash(emailHash);
        setPhoneEnc(phoneEnc);
        setPhoneHash(phoneHash);
        setNickname(nickname);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
